- src/main/java/fr/openent/supportpivot/Supportpivot.java
- src/main/java/fr/openent/supportpivot/constants/JiraConstants.java
- src/main/java/fr/openent/supportpivot/helpers/DateHelper.java
- src/main/java/fr/openent/supportpivot/services/JiraServiceImpl.java
change the format of the date,
and map the module from support to Jira component,
and set the reporter for the prod (assistance MLN).
> feat(support-pivot): #EV-269 change format date and map module for jira component

- src/main/java/fr/openent/supportpivot/constants/PivotConstants.java
- src/main/java/fr/openent/supportpivot/helpers/DateHelper.java
Change le format de la date et met à jour l'heure avec le fuseau horaire de paris.
> feat(support-pivot): #EV-269 change format date and set hour with time zone

- .github/workflows/dev-check-repository.yml
- .gitignore
- build.gradle
- build.sh
- gradle.properties
- src/test/java/fr/openent/supportpivot/helpers/DateHelperTest.java
- src/test/java/fr/openent/supportpivot/services/MongoServiceTest.java
- src/test/java/fr/openent/supportpivot/test/SimpleTest.java
ajout de test unitaire sur le MongoService et le DateHelper
ajout de dépendance pour les tests powerMock(2.0.2), mockito(2), junitVersion(4.12)
EV-269 https://entsupport.gdapublic.fr/browse/EV-269
> feat(support-pivot): #EV-269 add git action workflow and unit test

- LICENSE
- README.md
ajout d'une nouvelle licence et d'une description technique
merge après vérification de PO.
> docs: #CO-1641 add new licence and technical description

- README.md
- deployment/supportpivot/conf.json.template
- src/main/java/fr/openent/supportpivot/constants/EntConstants.java
- src/main/java/fr/openent/supportpivot/managers/ConfigManager.java
- src/main/java/fr/openent/supportpivot/model/endpoint/jira/JiraEndpoint.java
- src/main/java/fr/openent/supportpivot/services/JiraServiceImpl.java
- src/main/java/fr/openent/supportpivot/services/routers/CrifRouterService.java
Corrigez une faute de frappe dans la configuration et ajoutez un champ à la réponse de l'API
Pour éviter des erreurs on a décidé de ne pas changé les Magic String.
Tester l'API GET ticket et POST
> fix(): #EV-269 fix conf and lde api response

- src/main/java/fr/openent/supportpivot/constants/ConfigField.java
- src/main/java/fr/openent/supportpivot/constants/Field.java
- src/main/java/fr/openent/supportpivot/enums/PriorityEnum.java
- src/main/java/fr/openent/supportpivot/helpers/IModelHelper.java
- src/main/java/fr/openent/supportpivot/helpers/StringHelper.java
- src/main/java/fr/openent/supportpivot/model/ConfigModel.java
- src/main/java/fr/openent/supportpivot/model/IModel.java
- src/main/java/fr/openent/supportpivot/model/status/EntStatus.java
- src/main/java/fr/openent/supportpivot/model/status/JiraStatus.java
- src/main/java/fr/openent/supportpivot/model/status/StatusModel.java
- src/test/java/fr/openent/supportpivot/helpers/IModelHelperTest.java
- src/test/java/fr/openent/supportpivot/helpers/StringHelperTest.java
- src/test/java/fr/openent/supportpivot/model/ConfigModelTest.java
Création d'un model pour la config
[CO-1693](https://jira.support-ent.fr/browse/CO-1693)
> refacto(config): #CO-1693 create config model

- src/main/java/fr/openent/supportpivot/controllers/LdeController.java
- src/main/java/fr/openent/supportpivot/deprecatedservices/DefaultDemandeServiceImpl.java
- src/main/java/fr/openent/supportpivot/deprecatedservices/DefaultJiraServiceImpl.java
- src/main/java/fr/openent/supportpivot/managers/ConfigManager.java
- src/main/java/fr/openent/supportpivot/managers/ServiceManager.java
- src/main/java/fr/openent/supportpivot/model/ConfigModel.java
- src/main/java/fr/openent/supportpivot/model/endpoint/jira/JiraEndpoint.java
- src/main/java/fr/openent/supportpivot/model/ticket/JiraTicket.java
- src/main/java/fr/openent/supportpivot/services/HttpClientService.java
- src/main/java/fr/openent/supportpivot/services/JiraServiceImpl.java
- src/main/java/fr/openent/supportpivot/services/routers/CrifRouterService.java
- src/test/java/fr/openent/supportpivot/helpers/IModelHelperTest.java
- src/test/java/fr/openent/supportpivot/model/ConfigModelTest.java
- src/test/java/fr/openent/supportpivot/model/endpoint/jira/JiraEndpointTest.java
Using ConfigModel instead of JsonObject
[CO-1693](https://jira.support-ent.fr/browse/CO-1693)
> refacto(config): #CO-1693 refacto config to use model

- src/main/java/fr/openent/supportpivot/constants/BusConstants.java
- src/main/java/fr/openent/supportpivot/constants/ConfigField.java
- src/main/java/fr/openent/supportpivot/constants/JiraConstants.java
- src/main/java/fr/openent/supportpivot/controllers/LdeController.java
- src/main/java/fr/openent/supportpivot/controllers/SupportController.java
- src/main/java/fr/openent/supportpivot/deprecatedservices/DefaultDemandeServiceImpl.java
- src/main/java/fr/openent/supportpivot/deprecatedservices/DefaultJiraServiceImpl.java
- src/main/java/fr/openent/supportpivot/helpers/AsyncResultHelper.java
- src/main/java/fr/openent/supportpivot/helpers/EitherHelper.java
- src/main/java/fr/openent/supportpivot/helpers/PivotHttpClient.java
- src/main/java/fr/openent/supportpivot/helpers/PivotHttpClientRequest.java
- src/main/java/fr/openent/supportpivot/managers/ConfigManager.java
- src/main/java/fr/openent/supportpivot/managers/ServiceManager.java
- src/main/java/fr/openent/supportpivot/model/ConfigModel.java
- src/main/java/fr/openent/supportpivot/model/endpoint/LdeEndPoint.java
- src/main/java/fr/openent/supportpivot/model/endpoint/SupportEndpoint.java
- src/main/java/fr/openent/supportpivot/model/endpoint/jira/JiraEndpoint.java
- src/main/java/fr/openent/supportpivot/model/endpoint/jira/JiraFilterBuilder.java
- src/main/java/fr/openent/supportpivot/model/status/JiraStatus.java
- src/main/java/fr/openent/supportpivot/services/JiraServiceImpl.java
- src/main/java/fr/openent/supportpivot/services/MongoService.java
- src/main/java/fr/openent/supportpivot/services/routers/CrifRouterService.java
Added more logs and modified what already exists to be more detailed.
[CO-1699](https://jira.support-ent.fr/browse/CO-1699)
> refacto(log): #CO-1699 add better logs

- build.gradle
- src/main/java/fr/openent/supportpivot/model/endpoint/jira/JiraEndpoint.java
- src/main/java/fr/openent/supportpivot/services/JiraServiceImpl.java
- src/test/java/fr/openent/supportpivot/model/endpoint/jira/JiraEndpointTest.java
Use of JiraSearch and JiraTicket models.
Added dependency to mock private methods:
org.powermock:powermock-api-mockito2
org.powermock:powermock-module-junit4
org.powermock:powermock-module-testng
[CO-1702](https://jira.support-ent.fr/browse/CO-1702)
> feat(model): #CO-1702 use jiraticket model

- build.gradle
- src/main/java/fr/openent/supportpivot/constants/Field.java
- src/main/java/fr/openent/supportpivot/services/JiraServiceImpl.java
- src/main/java/fr/openent/supportpivot/services/routers/CrifRouterService.java
- src/test/java/fr/openent/supportpivot/services/JiraServiceImplTest.java
Rewrote the functions of a JiraService to be able to use JiraTicket model and PivotTicket model.
Added a dependency to pass the tests
io.vertx:vertx-codegen:3.9.5
[CO-1708](https://jira.support-ent.fr/browse/CO-1708)
> refactor: #CO-1708 use pivot ticket in jira service

- src/main/java/fr/openent/supportpivot/model/lde/LdePj.java
- src/main/java/fr/openent/supportpivot/model/lde/LdeTicket.java
Add a LdeTicket
[CO-1711](https://jira.support-ent.fr/browse/CO-1711)
> refactor: #CO-1711 create ldeticket model

- src/main/java/fr/openent/supportpivot/constants/Field.java
- src/main/java/fr/openent/supportpivot/controllers/LdeController.java
- src/main/java/fr/openent/supportpivot/controllers/SupportController.java
- src/main/java/fr/openent/supportpivot/helpers/PivotHttpClientRequest.java
- src/main/java/fr/openent/supportpivot/managers/ConfigManager.java
- src/main/java/fr/openent/supportpivot/managers/ServiceManager.java
- src/main/java/fr/openent/supportpivot/model/ConfigModel.java
- src/main/java/fr/openent/supportpivot/model/endpoint/LdeEndPoint.java
- src/main/java/fr/openent/supportpivot/model/endpoint/SupportEndpoint.java
- src/main/java/fr/openent/supportpivot/model/endpoint/jira/JiraEndpoint.java
- src/main/java/fr/openent/supportpivot/model/endpoint/jira/JiraFilterBuilder.java
- src/main/java/fr/openent/supportpivot/services/JiraServiceImpl.java
- src/main/java/fr/openent/supportpivot/services/MongoService.java
- src/main/java/fr/openent/supportpivot/services/routers/CrifRouterService.java
- src/main/java/fr/openent/supportpivot/services/routers/RouterService.java
- src/test/java/fr/openent/supportpivot/model/endpoint/jira/JiraEndpointTest.java
- src/test/java/fr/openent/supportpivot/services/JiraServiceImplTest.java
Use LdeTicket in the place of jsonObject
[CO-1712](https://jira.support-ent.fr/browse/CO-1712)
> refactor: #CO-1712 use ldeticket model

- src/main/java/fr/openent/supportpivot/constants/ConfigField.java
- src/main/java/fr/openent/supportpivot/managers/ConfigManager.java
- src/main/java/fr/openent/supportpivot/model/ConfigModel.java
> refactor: rename config field

- src/main/java/fr/openent/supportpivot/constants/Field.java
- src/main/java/fr/openent/supportpivot/controllers/JiraController.java
- src/main/java/fr/openent/supportpivot/controllers/LdeController.java
- src/main/java/fr/openent/supportpivot/controllers/SupportController.java
- src/main/java/fr/openent/supportpivot/helpers/FutureHelper.java
- src/main/java/fr/openent/supportpivot/helpers/HttpClientResponseHelper.java
- src/main/java/fr/openent/supportpivot/model/endpoint/AbstractEndpoint.java
- src/main/java/fr/openent/supportpivot/model/endpoint/Endpoint.java
- src/main/java/fr/openent/supportpivot/model/endpoint/LdeEndPoint.java
- src/main/java/fr/openent/supportpivot/model/endpoint/SupportEndpoint.java
- src/main/java/fr/openent/supportpivot/model/endpoint/jira/JiraEndpoint.java
- src/main/java/fr/openent/supportpivot/model/lde/LdeTicket.java
- src/main/java/fr/openent/supportpivot/services/HttpClientService.java
- src/main/java/fr/openent/supportpivot/services/JiraService.java
- src/main/java/fr/openent/supportpivot/services/JiraServiceImpl.java
- src/main/java/fr/openent/supportpivot/services/MongoService.java
- src/main/java/fr/openent/supportpivot/services/routers/CrifRouterService.java
- src/main/java/fr/openent/supportpivot/services/routers/RouterService.java
- src/test/java/fr/openent/supportpivot/model/endpoint/jira/JiraEndpointTest.java
Changed future handlers to improve readability.
[CO-1714](https://jira.support-ent.fr/browse/CO-1714)
> refactor: #CO-1714 pass handlers to future

- src/main/java/fr/openent/supportpivot/model/endpoint/LdeEndPoint.java
- src/main/java/fr/openent/supportpivot/model/endpoint/jira/JiraEndpoint.java
- src/main/java/fr/openent/supportpivot/model/jira/JiraFields.java
- src/main/java/fr/openent/supportpivot/model/pivot/PivotTicket.java
- src/main/java/fr/openent/supportpivot/services/JiraService.java
- src/main/java/fr/openent/supportpivot/services/JiraServiceImpl.java
- src/main/java/fr/openent/supportpivot/services/routers/CrifRouterService.java
- src/test/java/fr/openent/supportpivot/model/endpoint/jira/JiraEndpointTest.java
- src/test/java/fr/openent/supportpivot/services/JiraServiceImplTest.java
Use of JiraTicket and PivotTicket models + bug fix on JiraTicket json formatting
> refactor: use model and deletion of associated todo

- src/main/java/fr/openent/supportpivot/Supportpivot.java
- src/main/java/fr/openent/supportpivot/controllers/JiraController.java
- src/main/java/fr/openent/supportpivot/controllers/LdeController.java
- src/main/java/fr/openent/supportpivot/controllers/SupportController.java
- src/main/java/fr/openent/supportpivot/managers/ServiceManager.java
- src/main/java/fr/openent/supportpivot/model/endpoint/EndpointFactory.java
- src/main/java/fr/openent/supportpivot/model/endpoint/jira/JiraEndpoint.java
- src/main/java/fr/openent/supportpivot/services/HttpClientService.java
- src/main/java/fr/openent/supportpivot/services/MongoService.java
- src/main/java/fr/openent/supportpivot/services/RouterService.java
- src/main/java/fr/openent/supportpivot/services/impl/CrifRouterService.java
- src/main/java/fr/openent/supportpivot/services/impl/HttpClientServiceImpl.java
- src/main/java/fr/openent/supportpivot/services/impl/JiraServiceImpl.java
- src/main/java/fr/openent/supportpivot/services/impl/MongoServiceImpl.java
- src/test/java/fr/openent/supportpivot/model/endpoint/jira/JiraEndpointTest.java
- src/test/java/fr/openent/supportpivot/services/JiraServiceImplTest.java
- src/test/java/fr/openent/supportpivot/services/MongoServiceTest.java
Improve servicemanager and services. Refactor to respect convention.
[CO-1721](https://jira.support-ent.fr/browse/CO-1721)
> refactor: #CO-1721 improve servicemanager and services

- src/main/java/fr/openent/supportpivot/helpers/StringHelper.java
- src/main/java/fr/openent/supportpivot/model/endpoint/jira/JiraEndpoint.java
- src/main/java/fr/openent/supportpivot/model/jira/JiraAuthor.java
- src/main/java/fr/openent/supportpivot/model/lde/LdeTicket.java
- src/main/java/fr/openent/supportpivot/services/impl/JiraServiceImpl.java
Implementation of the search by ID ent when you receive a ticket from the ENT.
Create a ticket then escalate it. It appears in Jira.
Post a comment. It is added in jira.
[CO-1732](https://jira.support-ent.fr/browse/CO-1732)
> fix(ent): #CO-1732 fix ticket escalation

- src/main/java/fr/openent/supportpivot/constants/Field.java
- src/main/java/fr/openent/supportpivot/controllers/JiraController.java
- src/main/java/fr/openent/supportpivot/controllers/LdeController.java
- src/main/java/fr/openent/supportpivot/controllers/SupportController.java
- src/main/java/fr/openent/supportpivot/managers/ConfigManager.java
- src/main/java/fr/openent/supportpivot/model/endpoint/jira/JiraEndpoint.java
- src/main/java/fr/openent/supportpivot/model/jira/JiraSearch.java
Using mongo services to track user actions.
[CO-1733](https://jira.support-ent.fr/browse/CO-1733)
> feat(mongo): #CO-1733 use mongo service

- src/main/java/fr/openent/supportpivot/controllers/JiraController.java
- src/main/java/fr/openent/supportpivot/model/endpoint/SupportEndpoint.java
- src/main/java/fr/openent/supportpivot/model/ent/SupportTicket.java
Remove api security, making it unusable.
Update an issue on Jira and escalate it
[CO-1736](https://jira.support-ent.fr/browse/CO-1736)
> feat: #CO-1736 add scaled jira to ent

- src/main/java/fr/openent/supportpivot/controllers/LdeController.java
- src/main/java/fr/openent/supportpivot/model/endpoint/jira/JiraEndpoint.java
- src/main/java/fr/openent/supportpivot/model/endpoint/jira/JiraFilterBuilder.java
- src/main/java/fr/openent/supportpivot/model/jira/JiraSearch.java
- src/test/java/fr/openent/supportpivot/model/endpoint/jira/JiraEndpointTest.java
Add maxResults to filter the number of result send by Jira.
Call the LDE ticket listing API with the maxResults parameters.
[CO-1737](https://jira.support-ent.fr/browse/CO-1737)
> feat(lde): #CO-1737 add maxResults to filter the number of result

- src/main/java/fr/openent/supportpivot/model/lde/LdeTicket.java
Add creation and modification field in lde list api
API: https://confluence-test.support-ent.fr/display/MSP/Test+OpenAPI#/LdeController/get_supportpivot_lde_tickets
[CO-1743](https://jira.support-ent.fr/browse/CO-1743)
> feat(lde): #CO-1743 add creation and modification field in lde list api

- src/main/java/fr/openent/supportpivot/model/endpoint/jira/JiraFilterBuilder.java
- src/test/java/fr/openent/supportpivot/model/endpoint/jira/JiraEndpointTest.java
Add order by when call Jira API of listing ticket
[CO-1746](https://jira.support-ent.fr/browse/CO-1746)
> feat(lde): #CO-1746 add order by in list of lde results

- src/main/java/fr/openent/supportpivot/controllers/JiraController.java
Add "@SecuredAction(value = "", type = ActionType.AUTHENTICATED)" to updateTicketJira method in jiraController
- Try  @Get("/updateJira/:idjira") endpoint while not authenticated to check if you are blocked
[CO-1666](https://jira.support-ent.fr/browse/CO-1666)
> fix(secured-action): #CO-1666 add secured action authenticated to updateticketjira
